{% set name = "perl-test-warnings" %}
{% set version = "0.038" %}
{% set sha256 = "3da27e003a3c3cafed3c09b42be05cf9bdbff0bee5c8590a731b02853880a273" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Test::Warnings

about:
  home: https://github.com/karenetheridge/Test-Warnings
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENCE
  summary: 'Test for warnings and the lack of them'

extra:
  recipe-maintainers:
    - xileF1337
    - conda-forge/perl-packagers
